# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-16 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='total_questinos',
            new_name='total_questions',
        ),
    ]
